### ISSUE TITLE
Infer sample metadata from data itself with HTSinfer

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp#44]
**Is your feature request related to a problem? Please describe.**

Currently, metadata for each sample has to be determined and put in a sample table, which is tedious.

**Describe the solution you'd like**

We can call [HTSinfer](https://github.com/zavolanlab/htsinfer) and have the tool sniff the missing metadata. As HTSinfer does not estimate fragment size distributions, for single-ended libraries we should set a "reasonable" default here, if the user does not provide them.

Note that this is a meta-issue, as it will require several changes, at least the following (prepare one issue each for the following):

- [ ] Publish HTSinfer on Conda and BioContainers.
- [ ] Create a rule that runs HTSinfer
- [ ] Parse original sample table and call HTSinfer rule accordingly (no need to call it with all functionalities for all samples if metadata was already supplied; rule or bare Python code)
- [ ] Prepare an updated sample table (or dictionary that Snakemake can access?) from the output (rule or bare Python code)
- [ ] Read values from updated table or dictionary across entire pipeline

**Additional context**

Originally, we were thinking of integrating HTSinfer into [ZARP-cli](https://github.com/zavolanlab/zarp-cli). However, as it is potentially a long-running tool, it is better to run it as part of the pipeline in its own environment.

**Comment by uniqueg** [comment]
So while there are still some things to do in HTSinfer, the API should be more or less stable and it will be possible to go ahead with its integration.

The call to HTSinfer should look something like this:

```
htsinfer \
  --records=100000 \
  --output-directory=<PATH> \
  --temporary-directory=<PATH> \
  --cleanup-regime=KEEP_ALL \
  --threads=<INT> \
  <PATH_1> [<PATH_2>] \
  > <PATH>
```

Values in angular brackets will need to be supplied. `<PATH_2>` is for supplying the second mate of a paired-end library, so that's optional. The output will be a text file containing a JSON object, so best to name it something liike `htsinfer_<SAMPLE_ID>.json`.

The output will look like this:

```json
{"library_type": {"file_1": "first_mate", "file_2": "first_mate", "relationship": "not_mates"}, "library_source": {"file_1": {"name": "hsapiens", "taxon_id": "9606"}, "file_2": {"name": "hsapiens", "taxon_id": "9606"}}, "read_orientation": {"file_1": "SF", "file_2": "SR", "relationship": "ISF"}, "read_layout": {"file_1": {"adapt_3": "AATGATACGGCGACC"}, "file_2": {"adapt_3": "AATGATACGGCGACC"}}}
```

Prettified, that is:

```json
{
   "library_type":{
      "file_1":"first_mate",
      "file_2":"first_mate",
      "relationship":"not_mates"
   },
   "library_source":{
      "file_1":{
         "name":"hsapiens",
         "taxon_id":"9606"
      },
      "file_2":{
         "name":"hsapiens",
         "taxon_id":"9606"
      }
   },
   "read_orientation":{
      "file_1":"SF",
      "file_2":"SR",
      "relationship":"ISF"
   },
   "read_layout":{
      "file_1":{
         "adapt_3":"AATGATACGGCGACC"
      },
      "file_2":{
         "adapt_3":"AATGATACGGCGACC"
      }
   }
}
```
